os: linux
dist: xenial
language: ruby
rvm:
    - 2.6.5
cache: bundler
strategy: git

script: scripts/cibuild.sh

deploy:
    local_dir: _site/
    provider: pages:git
    edge: true
    token: $GITHUB_TOKEN
