source 'https://rubygems.org'
ruby '2.6.5'

gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-archives', github: 'jekyll/jekyll-archives'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown'
gem 'puma'
gem 'rack-jekyll'
gem 'rake'
