source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-archives', github: 'jekyll/jekyll-archives'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jemoji'
gem 'kramdown'
gem 'puma'
